# common variable values
org_name: wowzaaa 
app_name: rpfs

# Network variable values
network_cidr_block: "10.0.0.0/16"

# subnet variable values
subnet_conf:
  subnet_1:
    cidr_block: "10.0.1.0/24"
    network_zone: "eu-central"

# Firewall Configuration
firewall_conf:
  rules:
    rule_1:
      direction: "in"
      protocol: "tcp"
      port: "80"
      source_ips: ["0.0.0.0/0"]
      destination_ips: []
      description: "Allow HTTP inbound"
    rule_2:
      direction: "in"
      protocol: "tcp"
      port: "443"
      source_ips: ["0.0.0.0/0"]
      destination_ips: []
      description: "Allow HTTPS inbound"
    rule_3:
      direction: "in"
      protocol: "tcp"
      port: "5001"
      source_ips: ["0.0.0.0/0"]
      destination_ips: []
      description: "Allow 5001 inbound"
    rule_4:
      direction: "in"
      protocol: "tcp"
      port: "22"
      source_ips: ["0.0.0.0/0"]
      destination_ips: []
      description: "Allow SSH inbound"
    rule_5:
      direction: "in"
      protocol: "tcp"
      port: "9094"
      source_ips: ["0.0.0.0/0"]
      destination_ips: []
      description: "Allow 9094 inbound"
    rule_6:
      direction: "in"
      protocol: "tcp"
      port: "4001-4005"
      source_ips: ["0.0.0.0/0"]
      destination_ips: []
      description: "Allow 4001-4005 inbound"
    rule_7:
      direction: "out"
      protocol: "tcp"
      port: "any"
      source_ips: []
      destination_ips: ["0.0.0.0/0"]
      description: "Allow outbound Rule"

# Server Configuration
server_conf:
  master:
    server_type: "cx22"
    image: "ubuntu-24.04"
    location: "fsn1"
    backups: false
    delete_protection: false
    rebuild_protection: false
  slave-1:
    server_type: "cx22"
    image: "ubuntu-24.04"
    location: "fsn1"
    backups: false
    delete_protection: false
    rebuild_protection: false
  
# Add volume configurations
volume_conf:
  master-vol:
    size: 05
    location: "fsn1"
    format: "ext4"
    automount: false 
    delete_protection: false
  slave-vol:
    size: 05
    location: "fsn1"
    format: "ext4"
    automount: false 
    delete_protection: false

# Add volume attachment configurations
volume_attachments:
  master-attachment:
    volume_key: "master-vol"
    server_key: "master"
    automount: true
  slave-attachment:
    volume_key: "slave-vol"
    server_key: "slave-1"
    automount: true 