name: Deploy to Terraform
on:
  push:
    branches: ['main', 'develop']

# Jobs to be executed in the workflow
jobs:
  terraform-apply-stokenet:
    name: "Terraform apply"
    if: ${{ github.ref_name == 'develop'}}
    uses: ankushjha-aj/rpfs-hcloud/.github/workflows/workflow-trigger.yaml@develop
    with:
      workflow: apply 
      ref: ${{ github.ref }} 
      inputs: |
        env: stokenet
        ref: ${{ github.sha }}  
    secrets:
      GH_INFRA_PAT: ${{ secrets.GH_INFRA_PAT }}

  terraform-apply-mainnet:
    name: "test-condition" 
    if: ${{ github.ref_name == 'main'}}
    uses: ankushjha-aj/rpfs-hcloud/.github/workflows/workflow-trigger.yaml@develop
    with:
      workflow: apply 
      ref: ${{ github.ref }} 
      inputs: |
        env: stokenet
        ref: ${{ github.sha }}  
    secrets:
      GH_INFRA_PAT: ${{ secrets.GH_INFRA_PAT }}
