name: Deploy to Terraform
on:
  push:
    branches: ['main', 'develop']

# Jobs to be executed in the workflow
jobs:
# Job for applying Terraform in the stokenet environment.
  terraform-apply-stokenet:
    name: "Terraform apply"
    #if: ${{ github.ref_name == 'develop'}}
    uses: ankushjha-aj/rpfs-hcloud/.github/workflows/workflow-trigger.yaml@makefile  

    # Input parameters for the job
    with:
      workflow: terraform-apply # Triggering the 'apply' workflow
      ref: ${{ github.ref }} # Using the Git reference from the push event
      inputs: |
        env: stokenet # Using the environment from the push event
        ref: ${{ github.sha }} # Using the Git SHA from the push event

    # Secrets needed for the job (GH_INFRA_PAT)
    secrets:
      GH_INFRA_PAT: ${{ secrets.GH_INFRA_PAT }}

