name: Deploy to Terraform
on:
  push:
    branches: ['main', 'develop', 'makefile']

# Jobs to be executed in the workflow
jobs:
  terraform-apply-stokenet:
    name: "Terraform apply Stokenet"
    if: ${{ github.ref_name == 'develop'}}
    uses: ankushjha-aj/rpfs-hcloud/.github/workflows/workflow-trigger.yaml@makefile 

    with:
      workflow: apply 
      ref: ${{ github.ref }} 
      inputs: |
        env: stokenet
        ref: ${{ github.sha }} 
    secrets:
      GH_INFRA_PAT: ${{ secrets.GH_INFRA_PAT }}