name: Trigger Workflow

on:
  workflow_call:
    inputs:
      ref:
        description: Git Ref
        required: true
        type: string
      workflow:
        description: 'Workflow name'
        required: true
        type: string
      workflow_inputs:
        description: 'Workflow inputs'
        required: true
        type: string
    secrets:
      GH_INFRA_PAT:
        required: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: "Dispatch (${{ inputs.workflow }})"
    steps:
      - name: Dispatch workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/${{ inputs.workflow }}.yaml/dispatches
          ref: ${{ inputs.ref }}
          inputs: ${{ fromJSON(inputs.workflow_inputs) }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_INFRA_PAT }}